config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/questions", to: 'pages#questions'
  get "/liked_by", to: 'pages#liked_by'
  resources :profiles
  resources :user_answers, only: [:create, :update]
  resources :user_interactions, only: [:create]
  resources :groups, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :group_members, only: [:index, :create, :destroy]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :group_members, dependent: :destroy
  has_many :groups, through: :group_members
  has_many :group_as_master, dependent: :nullify, foreign_key: :master_id, class_name: "Group"
  has_many :user_answers, dependent: :destroy
  has_many :answers, through: :user_answers
  has_many :interactions_as_target, dependent: :destroy, foreign_key: :target_user_id, class_name: "UserInteraction"
  has_many :user_interactions, dependent: :destroy, foreign_key: :action_user_id, class_name: "UserInteraction"
  has_one_attached :photo

  validates :nickname, presence: true, uniqueness: true, length: {minimun: 3, maximum: 15}
  validates :first_name, presence: true, length: {minimun: 3, maximum: 50}
  validates :last_name, presence: true, length: {minimun: 3, maximum: 50}
  validates :description, length: {minimun: 5, maximum: 2000}
  validates :gender, presence:true, inclusion: { in:
    [
      'Feminino',
      'Masculino',
      'Trans homem',
      'Trans mulher',
      'Travesti',
      'Transgênero',
      'Homem transexual',
      'Pessoa trans',
      'Mulher transexual',
      'Pessoa transexual',
      'Mulher (trans)',
      'Homem (trans)',
      'Neutro',
      'Sem gênero',
      'Cross gender',
      'Mtf (homem que está em transição para o gênero feminino)',
      'Ftm (mulher que está em transição para o gênero masculino)'
    ]
  }
  validates :favorite_role, presence: true, inclusion: {in: ['Narrador', 'Jogador' ] }

  def compare_answers(current_user)
    user_answers = self.user_answers.map do |ua|
      ua.answer_id
    end

    q_size = user_answers.count.to_f
    return "" if q_size == 0

    current_user_answers = current_user.profile.user_answers.map do |ua|
      ua.answer_id
    end

    in_commom = (user_answers & current_user_answers).count.to_f
    return "#{(in_commom/q_size*100).to_i}%"
  end

  def something_new?
    self.group_members.find_by(viewed: false) ? true : false
  end



end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = policy_scope(Profile).where.not(id: current_user.profile.id)
    @user_interaction = UserInteraction.new
  end

  def new
    @profile = Profile.new
    @user = current_user
    authorize @profile
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    authorize @profile
    if @profile.save
      redirect_to profile_path(@profile)
    else
      render :new
    end
  end

  def show
    set_profile
  end

  def edit
  end

  def update
    @profile.update(profile_params)
    if @profile.save
      redirect_to profile_path(@profile)
    else
      render :new
    end
  end

  def destroy
    @profile.user.destroy
    redirect_to root_path
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
    authorize @profile
  end

  def profile_params
    params.require(:profile).permit(:nickname, :first_name, :last_name, :description, :gender, :favorite_role, :country, :state, :city, :photo)
  end
end

app/views/profiles/edit.html.erb
<div class = 'container'>
  <div class = col-12>
    <h4> Por favor, complete seu cadastro </h4>
    <%= simple_form_for (@profile) do |f| %>
      <%= f.input :nickname, label:'Escolha como quer ser chamado' %>
      <%= f.input :first_name, label: 'Seu Nome' %>
      <%= f.input :last_name, label: 'Seu Sobrenome' %>
      <%= f.input :gender, label: "qual seu genero?", collection: [
          'Feminino', 
          'Masculino',
          'Trans homem',
          'Trans mulher',
          'Travesti',
          'Transgênero',
          'Homem transexual',
          'Pessoa trans',
          'Mulher transexual',
          'Pessoa transexual',
          'Mulher (trans)',
          'Homem (trans)',
          'Neutro',
          'Sem gênero',
          'Cross gender',
          'Mtf (homem que está em transição para o gênero feminino)',
          'Ftm (mulher que está em transição para o gênero masculino)'
        ], class: "customRadio1"%>
      <%= f.input :favorite_role, label: "Como prefere jogar?", collection: ['Narrador', 'Jogador' ], as: :radio_buttons %>
      <%= f.input :country, label: "Seu país" %>
      <%= f.input :state, label: "Estado" %>
      <%= f.input :city, label: "Cidade" %>
      <%= f.input :description, label: 'Fale um pouco sobre você', as: :text%>
      <%= f.input :photo, as: :file %>
      <%= f.submit 'Enviar dados', class: 'btn btn-primary btn-block'%>
    <% end %>
         <%= link_to "Excluir Conta", profile_path(@profile),
                   method: :delete,
                   data: { confirm: "Tem certeza de que quer excluir seu perfil?" }, class:"btn btn-danger"%>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <% @profiles.each do |profile| %>
      <% if UserInteraction.all.where(action_user: current_user.profile).where(target_user: profile).length.zero?%>
        <div class="user-card">
          <div class="title">
            <h3><%= link_to profile.nickname, profile_path(profile)%></h3>
            <span class='affinity-score'><%= profile.compare_answers(current_user) %></span>
          </div>
          <div class="picture">
            <% if profile.photo.attached? %>
              <%=link_to (cl_image_tag profile.photo.key, height: 150, width: 200, crop: :fill),  profile_path(profile) %>
            <% else %>
              <%=link_to (image_tag "avatar-placeholder.gif", height: 150, width: 200, crop: :fill),  profile_path(profile) %>
            <% end %>
          </div>
          <p> <%= profile.description %> </p>
          <div class="interaction">
            <%= button_to 'X', { :controller => "user_interactions", :action => "create", user_interaction: { :liked => false, :target_user_id => profile.id } }, :method=>:post, class: "dislike-btn" %>
            <%= button_to 'O', { :controller => "user_interactions", :action => "create", user_interaction: { :liked => true, :target_user_id => profile.id } }, :method=>:post, class: "like-btn" %>
          </div>
        </div>
      <%end%>
    <%end%>
  </div>
</div>

app/views/profiles/new.html.erb
<div class = 'container'>
  <div class = 'col-12'>
    <h4> Por favor, complete seu cadastro </h4>
    <%= simple_form_for (@profile) do |f| %>
      <%= f.input :nickname, label:'Escolha como quer ser chamado' %>
      <%= f.input :first_name, label: 'Seu Nome' %>
      <%= f.input :last_name, label: 'Seu Sobrenome' %>
      <%= f.input :gender, label: "qual seu genero?", collection: [
          'Feminino',
          'Masculino',
          'Trans homem',
          'Trans mulher',
          'Travesti',
          'Transgênero',
          'Homem transexual',
          'Pessoa trans',
          'Mulher transexual',
          'Pessoa transexual',
          'Mulher (trans)',
          'Homem (trans)',
          'Neutro',
          'Sem gênero',
          'Cross gender',
          'Mtf (homem que está em transição para o gênero feminino)',
          'Ftm (mulher que está em transição para o gênero masculino)'
        ], class: "customRadio1"%>
      <%= f.input :favorite_role, label: "Como prefere jogar?", collection: ['Narrador', 'Jogador' ], as: :radio_buttons %>
      <%= f.input :country, label: "Seu país" %>
      <%= f.input :state, label: "Estado" %>
      <%= f.input :city, label: "Cidade" %>
      <%= f.input :description, label: 'Fale um pouco sobre você', as: :text%>
      <%= f.input :photo, as: :file %>
      <%= f.submit 'Enviar dados', class: 'btn btn-primary btn-block'%>
    <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container d-flex justify-content-between">
  <div class="cards">
    <div class="card-profile">
      <div class="profile-title">
        <h2><%=@profile.first_name%> <%=@profile.last_name%></h2>
      </div>
      <div class="photo-box">
        <% if @profile.photo.attached? %>
            <%= cl_image_tag @profile.photo.key, height: 225, width: 275, crop: :fill %>
          <% else %>
            <%= image_tag "avatar-placeholder.gif", height: 225, width: 275, crop: :fill %>
        <% end %>
      </div>
      <div class="col-md-auto">
        <div class="box-info">
          <h1><%=@profile.nickname%></h1>
          <h3><%=@profile.favorite_role%></h3>
          <p><%= @profile.gender %></p>
          <p><%= @profile.country %></p>
          <p><%= @profile.state %></p>
          <p><%= @profile.city %></p>
        </div>
      </div>

    </div>
  </div>
    <div class="profile-info">
      <div class="box-quote">
         <h1><%= @profile.description %></h1>
      </div>
      <div class="btn-chat">
        <% if current_user.profile == @profile%>
          <%= link_to "Editar Perfil", edit_profile_path(@profile), class: "btn btn-primary"%>
        <% end %>
        <%= link_to "Back to Profiles", profiles_path, class: "btn btn-primary"%>
      </div>
    </div>
</div>