config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/questions", to: 'pages#questions'
  get "/liked_by", to: 'pages#liked_by'
  resources :profiles
  resources :user_answers, only: [:create, :update]
  resources :user_interactions, only: [:create]
  resources :groups, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :group_members, only: [:index, :create, :destroy]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :master, class_name: :Profile, optional: true
  has_many :group_members, dependent: :destroy
  has_one :chatroom
  has_one_attached :photo
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update]

  def index
    @groups = policy_scope(Group)
    @user_groups = current_user.profile.groups
    @new_groups = current_user.profile.group_members.where(viewed: false).map { |gm| gm.group }
  end

  def edit
    @group_members =  @group.group_members.map{ |member| member.profile}
    #@group_members = @group.group_members
  end

  def update
    @group.update(group_params)
    redirect_to groups_path
  end

  def show
    set_group
  end
end


private

  def group_params
    params.require(:group).permit(:master_id, :name, :description, :game_system, :photo)
  end

  def set_group
    @group = Group.find(params[:id])
    authorize @group
  end

app/views/groups/edit.html.erb
<div class = "container">
  <h1>Deixe o seu grupo mais Único</h1>
  <%= simple_form_for @group do |f| %>
    <%= f.input :name %>
    <%= f.association :master, collection: @group_members , label_method: :nickname, value_method: :id, include_hidden: false %>
    <%= f.input :description %>
    <%= f.input :game_system %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>

  <%= link_to "voltar a Grupos", groups_path %>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="cards">
    <% @user_groups.each do |group| %>
      <div class="card-group">

      <div class="group-title">
      <h1> <%= link_to group.name, group_path(group)%></h1>
      <div class="group-photo-box">
        <% if group.photo.attached? %>
        <%=link_to (cl_image_tag group.photo.key, height: 149, width: 184, crop: :fill) %>
        <% else %>
        <%=link_to (image_tag "icon.png", height: 149, width: 184, crop: :fill) %>
        <% end %>
      </div>
        <div class="box-info-group">
          <% group.group_members.each do |member|%>
          <% member.been_viewed if member.profile == current_user.profile %>
          <div class="group-member">
            <% if member.profile.photo.attached? %>
              <%=link_to (cl_image_tag member.profile.photo.key, crop: :fill, class: "avatar-square"),  profile_path(member.profile) %>
            <% else %>
              <%=link_to (image_tag "avatar-placeholder.gif", crop: :fill, class: "avatar-square"),  profile_path(member.profile) %>
            <% end %>
            <% if member.profile == group.master %>
              <h3><b><%= link_to member.profile.nickname, profile_path(member.profile)%></b></h3>
            <% else %>
              <h3> <%= link_to member.profile.nickname, profile_path(member.profile) %> </h3>
            <% end %>

          </div>
          <% end %>
        </div>
          <div class="btn-chat">
            <% if group.chatroom %>
              <%= link_to "Conversar", chatroom_path(group.chatroom), class: "btn btn-primary"%>
            <% end %>
          </div>

        <div class="btn-edit">
        <% if group.master == current_user.profile %>
          <%= link_to "Editar", edit_group_path(group), class: "btn btn-primary" %>
        <% end %>
        </div>

      </div>
      </div>



    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="cards">
    <% group = @group %>
      <div class="card-group-show">

      <div class="group-title-show">
      <h1> <%= group.name %>  </h1>
      <div class="group-photo-box-show">
        <% if group.photo.attached? %>
        <%=link_to (cl_image_tag group.photo.key, height: 225, width: 275, crop: :fill) %>
        <% else %>
        <%=link_to (image_tag "icon.png", height: 225, width: 275, crop: :fill) %>
        <% end %>
      </div>
        <div class="box-info-group-show">
          <% group.group_members.each do |member|%>
          <% member.been_viewed if member.profile == current_user.profile %>
          <div class="group-member-show">
            <% if member.profile.photo.attached? %>
              <%=link_to (cl_image_tag member.profile.photo.key, crop: :fill, class: "avatar-square"),  profile_path(member.profile) %>
            <% else %>
              <%=link_to (image_tag "avatar-placeholder.gif", crop: :fill, class: "avatar-square"),  profile_path(member.profile) %>
            <% end %>
            <% if member.profile == group.master %>
              <h3><b><%= link_to member.profile.nickname, profile_path(member.profile)%></b></h3>
              <p> <%= member.profile.city %> </p>
            <% else %>
              <h3> <%= link_to member.profile.nickname, profile_path(member.profile) %> </h3>
              <p>   -  <%= member.profile.city %> </p>
            <% end %>

          </div>
          <% end %>
          <div class="group-info-show">
            <h2>Mestre - <%= group.master.nil? ? "Sem mestre" : group.master&.nickname %> </h2>
            <p> <%= group.description %> </p>
            <p>Sistema: <%= group.game_system %></p>
          </div>
        </div>
          <div class="btn-chat-show">
            <% if group.chatroom %>
              <%= link_to "Conversar", chatroom_path(group.chatroom), class: "btn btn-primary"%>
            <% end %>
          </div>

        <div class="btn-edit-show">
        <% if group.master == current_user.profile %>
          <%= link_to "Editar", edit_group_path(group), class: "btn btn-primary" %>
        <% end %>
        </div>

      </div>
      </div>




  </div>
</div>