config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/questions", to: 'pages#questions'
  get "/liked_by", to: 'pages#liked_by'
  resources :profiles
  resources :user_answers, only: [:create, :update]
  resources :user_interactions, only: [:create]
  resources :groups, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :group_members, only: [:index, :create, :destroy]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "icon.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", profiles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Quem quer jogar?", liked_by_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Meus Grupos", groups_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <span class=<%= current_user.profile&.something_new? ? 'newicon-avatar' : '' %>></span>
          <% if current_user.profile&.photo&.attached? %>
            <%= cl_image_tag current_user.profile.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown", user_id: current_user.id }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "avatar-placeholder.gif", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown", user_id: current_user.id }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.profile %>
              <%= link_to "Meu Perfil", profile_path(current_user.profile), class: "dropdown-item" %>
            <% end %>
            <div class="position-relative">
              <span class=<%= current_user.profile&.group_members&.find_by(viewed: false) ? 'newicon-menu' : '' %>></span>
              <%= link_to "Meus Grupos", groups_path, class: "dropdown-item" %>
            </div>
            <%= link_to "Aprimore seu perfil", questions_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>